#ifndef _CONFIG_H_
#define _CONFIG_H_

#define TELNET_PORT 23

#define DEFAULT_GEO_LAT 43.7167
#define DEFAULT_GEO_LON 10.4
#define ATM_PRESSURE 101.0 //kPa
#define ATM_TEMPERATURE 298.0 // K

#define DEFAULT_AZI_KP 10.
#define DEFAULT_AZI_KD 0.
#define DEFAULT_AZI_KI 0.

#define DEFAULT_ALT_KP 10.
#define DEFAULT_ALT_KD 0.
#define DEFAULT_ALT_KI 0.

#define DEFAULT_VOLT_TO_DEG (360.0/2.5)

//#define ALT_MOTOR_INVERTED
//#define AZI_MOTOR_INVERTED
#define ENCODER_OVERSAMPLING 1
#define DEFAULT_ALT_ENCODER_ZERO 0.0
#define DEFAULT_AZI_ENCODER_ZERO 0.0
#define DEFAULT_ALT_MIN_E 1.0
#define DEFAULT_AZI_MIN_E 1.0
// in deg/sec 
#define MIN_ALLOWED_SPEED .1
#define WATCHDOG_TIME_FACTOR 3.
#define DEFAULT_MIN_SPEED 80
#define DEFAULT_MIN_SPEED_VALUE 1.0
#define DEFAULT_MAX_SPEED_VALUE 16.0
#define DEFAULT_M_SPEED .3

#define MAX_SLEEP_S (2*3600)
#define SLEEP_TIME_S (10*60)
#define SAFETY_TIME_BEFORE_FIRST_SCENE 120
#define SAFETY_TIME_BEFORE_SEQUENCE (SAFETY_TIME_BEFORE_FIRST_SCENE+30)
#define WAKEUP_TIME_BEFORE_SCHEDULE_S (SAFETY_TIME_BEFORE_SEQUENCE+30)

// Timer for wifi connections in ms 
// #define WIFI_WATCHDOG_TIME (600000L) // 10 min
#define WIFI_WATCHDOG_TIME (300000L) // 5 min
//#define WIFI_WATCHDOG_TIME (60000L) // 1 min
//#define WIFI_WATCHDOG_TIME (10000L)

#define TELNET_WATCHDOG_TIME (60000L)

#define BATTERY_MIN_mV 9000.
#define BATTERY_MAX_mV 12600.
#define BATTERY_R1_kOHM 147.
#define BATTERY_R2_kOHM 10.
#define BATTERY_VOLTAGE_DIVIDER_FAC (BATTERY_R2_kOHM/(BATTERY_R2_kOHM+BATTERY_R1_kOHM))


#define MAX_LOG_FILES 120
// Delete a log file after number of days, -1 to keep everything
#define LOG_DELETE_AFTER_DAYS -1
#define LOG_LEVEL LOG_INFO
#define SERIAL_LOG_ENABLED
#define LITTLEFS_LOG_ENABLED

#endif